export const FETCH_ARTICLES_REQUEST = 'news/FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_SUCCESS = 'news/FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'news/FETCH_ARTICLES_ERROR'

export const CHANGE_SEARCH_TERM = 'news/CHANGE_SEARCH_TERM'
