export const FETCH_ARTICLES_REQUEST = 'news/FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_SUCCESS = 'news/FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'news/FETCH_ARTICLES_ERROR'

// export const FETCH_SOURCES_REQUEST = 'news/FETCH_SOURCES_REQUEST'
// export const FETCH_SOURCES_SUCCESS = 'news/FETCH_SOURCES_SUCCESS'
// export const FETCH_SOURCES_ERROR = 'news/FETCH_SOURCES_ERROR'
