export const FETCH_ARTICLES_SUCCESS = 'news/FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_REQUEST = 'news/FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_ERROR = 'news/FETCH_ARTICLES_ERROR'
export const SEARCH_ARTICLES_SUCCESS = 'news/SEARCH_ARTICLES_SUCCESS'
export const SEARCH_ARTICLES_REQUEST = 'news/SEARCH_ARTICLES_REQUEST'
export const SEARCH_ARTICLES_ERROR = 'news/SEARCH_ARTICLES_ERROR'
export const FETCH_TOP_ARTICLES_BY_CATEGORIES_REQUEST =
  'news/FETCH_TOP_ARTICLES_BY_CATEGORIES_REQUEST'
export const FETCH_TOP_ARTICLES_BY_CATEGORIES_SUCCESS =
  'news/FETCH_TOP_ARTICLES_BY_CATEGORIES_SUCCESS'
export const FETCH_TOP_ARTICLES_BY_CATEGORIES_ERROR =
  'news/FETCH_TOP_ARTICLES_BY_CATEGORIES_ERROR'
export const FETCH_ARTICLES_BY_CATEGORY_REQUEST =
  'news/FETCH_ARTICLES_BY_CATEGORY_REQUEST'
export const FETCH_ARTICLES_BY_CATEGORY_SUCCESS =
  'news/FETCH_ARTICLES_BY_CATEGORY_SUCCESS'
export const FETCH_ARTICLES_BY_CATEGORY_ERROR =
  'news/FETCH_ARTICLES_BY_CATEGORY_ERROR'
export const CHANGE_SEARCH_TERM = 'news/CHANGE_SEARCH_TERM'
